export const testDates = {
  '2022-09-16': {
    borderColor: null,
    cycleDay: 1,
    marked: true,
    selected: true,
    selectedColor: '#E37FB4',
    selectedTextColor: 'white',
    type: 'period',
  },
  '2022-09-17': {
    borderColor: null,
    cycleDay: 2,
    marked: true,
    selected: true,
    selectedColor: '#E37FB4',
    selectedTextColor: 'white',
    type: 'period',
  },
  '2022-09-18': {
    borderColor: null,
    cycleDay: 3,
    marked: true,
    selected: true,
    selectedColor: '#E37FB4',
    selectedTextColor: 'white',
    type: 'period',
  },
  '2022-09-19': {
    borderColor: null,
    cycleDay: 4,
    marked: true,
    selected: true,
    selectedColor: '#E37FB4',
    selectedTextColor: 'white',
    type: 'period',
  },
  '2022-09-20': {
    borderColor: null,
    cycleDay: 5,
    marked: true,
    selected: true,
    selectedColor: '#E37FB4',
    selectedTextColor: 'white',
    type: 'period',
  },
  '2022-09-21': {
    borderColor: null,
    cycleDay: 6,
    marked: true,
    selected: true,
    selectedColor: '#E37FB4',
    selectedTextColor: 'white',
    type: 'period',
  },
  '2022-09-22': {
    borderColor: null,
    cycleDay: 7,
    marked: true,
    selected: true,
    selectedColor: '#E37FB4',
    selectedTextColor: 'white',
    type: 'period',
  },
  '2022-09-23': {
    borderColor: null,
    cycleDay: 8,
    marked: true,
    selected: true,
    selectedColor: '#E37FB4',
    selectedTextColor: 'white',
    type: 'period',
  },
  '2022-09-24': {
    borderColor: null,
    cycleDay: 9,
    marked: true,
    selected: true,
    selectedColor: '#E37FB4',
    selectedTextColor: 'white',
    type: 'period',
  },
  '2022-09-25': {
    borderColor: null,
    cycleDay: 10,
    marked: true,
    selected: true,
    selectedColor: '#E37FB4',
    selectedTextColor: 'white',
    type: 'period',
  },
  '2022-09-28': {
    borderColor: '#D22328',
    cycleDay: 10,
    marked: true,
    selected: true,
    selectedColor: 'white',
    selectedTextColor: '#B7AFB9',
    type: 'sex',
  },
  '2022-10-07': {
    borderColor: null,
    cycleDay: 11,
    marked: true,
    selected: true,
    selectedColor: '#FFCC00',
    selectedTextColor: 'white',
    type: 'ovulation_f',
  },
  '2022-10-08': {
    borderColor: null,
    cycleDay: 11,
    marked: true,
    selected: true,
    selectedColor: '#9A8AC2',
    selectedTextColor: 'white',
    type: 'pms',
  },
  '2022-10-28': {
    borderColor: '#E37FB4',
    cycleDay: 12,
    marked: true,
    selected: true,
    selectedColor: '#FDFCFC',
    selectedTextColor: '#B7AFB9',
    type: 'period_f',
  },
  '2022-10-29': {
    borderColor: '#E37FB4',
    cycleDay: 13,
    marked: true,
    selected: true,
    selectedColor: '#FDFCFC',
    selectedTextColor: '#B7AFB9',
    type: 'period_f',
  },
  '2022-10-30': {
    borderColor: '#E37FB4',
    cycleDay: 14,
    marked: true,
    selected: true,
    selectedColor: '#FDFCFC',
    selectedTextColor: '#B7AFB9',
    type: 'period_f',
  },
  '2022-10-31': {
    borderColor: '#E37FB4',
    cycleDay: 15,
    marked: true,
    selected: true,
    selectedColor: '#FDFCFC',
    selectedTextColor: '#B7AFB9',
    type: 'period_f',
  },
  '2022-11-01': {
    borderColor: '#E37FB4',
    cycleDay: 16,
    marked: true,
    selected: true,
    selectedColor: '#FDFCFC',
    selectedTextColor: '#B7AFB9',
    type: 'period_f',
  },
  '2022-11-02': {
    borderColor: '#E37FB4',
    cycleDay: 17,
    marked: true,
    selected: true,
    selectedColor: '#FDFCFC',
    selectedTextColor: '#B7AFB9',
    type: 'period_f',
  },
  '2022-11-03': {
    borderColor: '#E37FB4',
    cycleDay: 18,
    marked: true,
    selected: true,
    selectedColor: '#FDFCFC',
    selectedTextColor: '#B7AFB9',
    type: 'period_f',
  },
  '2022-11-04': {
    borderColor: '#E37FB4',
    cycleDay: 19,
    marked: true,
    selected: true,
    selectedColor: '#FDFCFC',
    selectedTextColor: '#B7AFB9',
    type: 'period_f',
  },
  '2022-11-05': {
    borderColor: '#E37FB4',
    cycleDay: 20,
    marked: true,
    selected: true,
    selectedColor: '#FDFCFC',
    selectedTextColor: '#B7AFB9',
    type: 'period_f',
  },
  '2022-11-06': {
    borderColor: '#E37FB4',
    cycleDay: 21,
    marked: true,
    selected: true,
    selectedColor: '#FDFCFC',
    selectedTextColor: '#B7AFB9',
    type: 'period_f',
  },
};
